// Code generated by "stringer -type=Command"; DO NOT EDIT.

package wspace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Push-1]
	_ = x[Dup-2]
	_ = x[Copy-3]
	_ = x[Swap-4]
	_ = x[Discard-5]
	_ = x[Slide-6]
	_ = x[Add-7]
	_ = x[Sub-8]
	_ = x[Mul-9]
	_ = x[Div-10]
	_ = x[Mod-11]
	_ = x[Store-12]
	_ = x[Retrieve-13]
	_ = x[Mark-14]
	_ = x[Call-15]
	_ = x[Jump-16]
	_ = x[JZero-17]
	_ = x[JNeg-18]
	_ = x[Ret-19]
	_ = x[End-20]
	_ = x[WriteChar-21]
	_ = x[WriteNum-22]
	_ = x[ReadChar-23]
	_ = x[ReadNum-24]
}

const _Command_name = "PushDupCopySwapDiscardSlideAddSubMulDivModStoreRetrieveMarkCallJumpJZeroJNegRetEndWriteCharWriteNumReadCharReadNum"

var _Command_index = [...]uint8{0, 4, 7, 11, 15, 22, 27, 30, 33, 36, 39, 42, 47, 55, 59, 63, 67, 72, 76, 79, 82, 91, 99, 107, 114}

func (i Command) String() string {
	i -= 1
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
